```yaml
FROM tomcat:9.0.122-jdk8
RUN curl -fL -o /usr/local/tomcat/webapps/student.war  https://s3-us-west-2.amazonaws.com/studentapi-cit/student.war
RUN curl -fL -o /usr/local/tomcat/lib/mysql-connector.jar https://s3-us-west-2.amazonaws.com/studentapi-cit/mysql-connector.jar
COPY context.xml /usr/local/tomcat/conf/context.xml
EXPOSE 8080
CMD ["catalina.sh", "run"]
```
